PP-12123: Add jobs to build and push prometheus pushgateway resource
alphagov/pay-ci pull request #1049
Opened 2024-02-12 11:51 UTC by jfharden

Add a job to the prometheus-pushgateway pipeline to build and push the prometheus-pushgateway-resource to dockerhub.

Later, when we aren't just spiking on this it would be good to add some integration tests between candidate and confirmed release, but while we are spiking this minimal setup will do.

2024-02-12 12:55 UTC, rfisher-gds requested changes
a typo

2024-02-12 12:55 UTC, rfisher-gds commented on ci/pipelines/prometheus-pushgateway.yml
> +          LABEL_release_numer: ((.:release-number))
number

2024-02-12 14:38 UTC, jfharden commented on ci/pipelines/prometheus-pushgateway.yml
> +          LABEL_release_numer: ((.:release-number))
Fixed 👍 Good spot

2024-02-13 09:36 UTC, rfisher-gds approved these changes

2024-02-13 09:47 UTC, merged