PP-7687 Frontend production pipeline
alphagov/pay-ci pull request #406
Opened 2021-03-11 17:20 UTC by mrlumbu

Same as staging except without push to a further ECR at the end (this is the end of the line)

2021-03-11 17:36 UTC, oswaldquek requested changes
Would also be good to see a green build at https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy-to-production?group=frontend before approving.

2021-03-11 17:36 UTC, oswaldquek commented on ci/pipelines/deploy-to-production.yml
> +      <<: *aws_staging_config
this should be `aws_production_config`?

2021-03-11 17:36 UTC, oswaldquek commented on ci/pipelines/deploy-to-production.yml
> +      <<: *aws_staging_config
same as above

2021-03-11 17:36 UTC, oswaldquek commented on ci/pipelines/deploy-to-production.yml
> +    aws_region: eu-west-1
all these should be productionized

2021-03-12 09:26 UTC, mrlumbu commented
sorry, bit of an end of day PR. Fixed

2021-03-12 09:29 UTC, mrlumbu commented
The build will go green once your pay-infra changes are in master @oswaldquek

2021-03-12 09:37 UTC, oswaldquek approved these changes

2021-03-12 14:53 UTC, merged