Pp 7688 connector selfservice pipeline
alphagov/pay-ci pull request #411
Opened 2021-03-15 16:48 UTC by oswaldquek

Connector and selfservice pipeline for staging and prod.

2021-03-15 16:48 UTC, oswaldquek commented
Build currently fails for production deploys with
```
Error: Error creating IAM Role production-2-selfservice-FARGATE-iam_for_ecs_exec_ssm: AccessDenied: User: arn:aws:sts::092359438320:assumed-role/concourse/terraform-prod-assume-role is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::092359438320:role/production-2-selfservice-FARGATE-iam_for_ecs_exec_ssm
	status code: 403, request id: 5babcea8-47c7-412a-9653-362ed2c23883
```

2021-03-16 16:07 UTC, mrlumbu commented on ci/pipelines/deploy-to-production.yml
> +      repository: govukpay/cardid
```suggestion
      repository: govukpay/connector
```

2021-03-16 16:07 UTC, mrlumbu commented on ci/pipelines/deploy-to-production.yml
> +      repository: govukpay/cardid
```suggestion
      repository: govukpay/selfservice
```

2021-03-16 16:08 UTC, mrlumbu requested changes
Couple of typos

2021-03-17 09:31 UTC, mrlumbu approved these changes

2021-03-17 09:32 UTC, merged