PP-11028: Add timestamp tags to release images
alphagov/pay-ci pull request #888
Opened 2023-06-01 12:10 UTC by jonathan-ryding

Image build date labels and Concourse tags were previously added to candidate images in https://github.com/alphagov/pay-ci/pull/885 . This PR adds labels and tags to release images in the same way.

2023-06-01 13:59 UTC, jonathan-ryding commented on ci/pipelines/deploy-to-test.yml
> +          file: tags/date
Fixed

2023-06-07 12:37 UTC, katstevens commented on ci/pipelines/deploy-to-test.yml
> +          additional_tags: tags/all-release-tags
I don't think the `tasks/parse-release-tag.yml` job has an `all-release-tags` output file yet - the previous PR added `all-candidate-tags`?

2023-06-07 12:44 UTC, katstevens approved these changes

2023-06-07 13:51 UTC, jfharden requested changes
Some of the jobs aren't parsing the correct release number and end up with a release tag of `release-release`.

JR and I discussed it and I didn't think to comment on the PR :(

2023-06-07 13:55 UTC, jfharden approved these changes
Oh no, I take it back, the ones that are problematic were removed from the PR 👍

2023-07-24 11:42 UTC, merged